/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class InterfazRegistraPasajero extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistraPasajero
     */
    
    private Pasajero P = new Pasajero();
    private Avioni av = new Avioni();
    public InterfazRegistraPasajero() {
        initComponents();
//        this.av = av;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTNroAsiento = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTCi = new javax.swing.JTextField();
        jBRegistrarPasajero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Nro Asiento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Registro Pasajero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, 40));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Ci:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 30, 40));

        jTNroAsiento.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTNroAsiento.setText("0");
        jPanel1.add(jTNroAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 190, 40));

        jTNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 190, 40));

        jTCi.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTCi.setText("0");
        jPanel1.add(jTCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 40));

        jBRegistrarPasajero.setBackground(new java.awt.Color(0, 0, 0));
        jBRegistrarPasajero.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBRegistrarPasajero.setForeground(new java.awt.Color(255, 255, 255));
        jBRegistrarPasajero.setText("Agregar");
        jBRegistrarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarPasajeroActionPerformed(evt);
            }
        });
        jPanel1.add(jBRegistrarPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarPasajeroActionPerformed
        P.setNombre(jTNombre.getText());
        P.setCi(Integer.parseInt(jTCi.getText()));
        P.setNroAsiento(Integer.parseInt(jTNroAsiento.getText()));
//        System.out.println(jTNombre.getText());
        
        this.setVisible(false);
    }//GEN-LAST:event_jBRegistrarPasajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistraPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistraPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistraPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistraPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistraPasajero().setVisible(true);
            }
        });
    }

    public Pasajero getP() {
        return P;
    }

    public void setP(Pasajero P) {
        this.P = P;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRegistrarPasajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCi;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTNroAsiento;
    // End of variables declaration//GEN-END:variables
}
