/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class InterfazEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InterfazEmpleado
     */
    
    DefaultTableModel tabla = new DefaultTableModel();
    Empleado E1 = new Empleado();
    public InterfazEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDO");
        tabla.addColumn("GENERO");
        tabla.addColumn("FECHA NAC");
        tabla.addColumn("INGRESO");
        tabla.addColumn("SALARIO");
        jTMostrarEmpleado.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTGenero = new javax.swing.JTextField();
        jTFechaNac = new javax.swing.JTextField();
        jTFechaIngreso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBSalarioModificar = new javax.swing.JButton();
        jTSalario = new javax.swing.JTextField();
        jTSalarioModificar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBCalcularPrestacion = new javax.swing.JButton();
        jBCalcularEdad = new javax.swing.JButton();
        jBCalcularAntiguedad = new javax.swing.JButton();
        jTCalcularPrestacion = new javax.swing.JTextField();
        jTCalcularEdad = new javax.swing.JTextField();
        jTCalcularAntiguedad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBSalarioModificar3 = new javax.swing.JButton();
        jBSalarioModificar5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMostrarEmpleado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Salario:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Genero:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("Fecha Nac:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel7.setText("Fecha Ingreso:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, -1));

        jTApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));

        jTGenero.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, -1));

        jTFechaNac.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTFechaNac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));

        jTFechaIngreso.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTFechaIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 260, 290));

        jBSalarioModificar.setBackground(new java.awt.Color(0, 0, 0));
        jBSalarioModificar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBSalarioModificar.setForeground(new java.awt.Color(255, 255, 255));
        jBSalarioModificar.setText("Modificar Salario");
        jBSalarioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalarioModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBSalarioModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 40));

        jTSalario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 170, -1));

        jTSalarioModificar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTSalarioModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTSalarioModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 600, 310));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCalcularPrestacion.setBackground(new java.awt.Color(0, 0, 0));
        jBCalcularPrestacion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBCalcularPrestacion.setForeground(new java.awt.Color(255, 255, 255));
        jBCalcularPrestacion.setText("Calcular prestaciones");
        jBCalcularPrestacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularPrestacionActionPerformed(evt);
            }
        });
        jPanel2.add(jBCalcularPrestacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 110, 210, 40));

        jBCalcularEdad.setBackground(new java.awt.Color(0, 0, 0));
        jBCalcularEdad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBCalcularEdad.setForeground(new java.awt.Color(255, 255, 255));
        jBCalcularEdad.setText("Calcular Edad");
        jBCalcularEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularEdadActionPerformed(evt);
            }
        });
        jPanel2.add(jBCalcularEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 40));

        jBCalcularAntiguedad.setBackground(new java.awt.Color(0, 0, 0));
        jBCalcularAntiguedad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBCalcularAntiguedad.setForeground(new java.awt.Color(255, 255, 255));
        jBCalcularAntiguedad.setText("Calcular Antiguedad");
        jBCalcularAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularAntiguedadActionPerformed(evt);
            }
        });
        jPanel2.add(jBCalcularAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 210, 40));

        jTCalcularPrestacion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTCalcularPrestacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTCalcularPrestacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 230, 40));

        jTCalcularEdad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTCalcularEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTCalcularEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 230, 40));

        jTCalcularAntiguedad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTCalcularAntiguedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTCalcularAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 230, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 600, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBSalarioModificar3.setBackground(new java.awt.Color(0, 0, 0));
        jBSalarioModificar3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBSalarioModificar3.setForeground(new java.awt.Color(255, 255, 255));
        jBSalarioModificar3.setText("Agregar");
        jBSalarioModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalarioModificar3ActionPerformed(evt);
            }
        });

        jBSalarioModificar5.setBackground(new java.awt.Color(0, 0, 0));
        jBSalarioModificar5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBSalarioModificar5.setForeground(new java.awt.Color(255, 255, 255));
        jBSalarioModificar5.setText("Mostrar");
        jBSalarioModificar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalarioModificar5ActionPerformed(evt);
            }
        });

        jTMostrarEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTMostrarEmpleado);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBSalarioModificar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSalarioModificar5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalarioModificar3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalarioModificar5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 600, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalarioModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalarioModificar3ActionPerformed
        E1.setNombre(jTNombre.getText());
        E1.setApellido(jTApellido.getText());
        E1.setGenero(jTGenero.getText());
        E1.setFechaNac(jTFechaNac.getText());
        E1.setFechaIngresoEmpresa(jTFechaIngreso.getText());
        E1.setSalario(Double.parseDouble(jTSalario.getText()));
        jTNombre.setText("");
        jTApellido.setText("");
        jTGenero.setText("");
        jTFechaNac.setText("");
        jTFechaIngreso.setText("");
        jTSalario.setText("");
        
    }//GEN-LAST:event_jBSalarioModificar3ActionPerformed

    private void jBSalarioModificar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalarioModificar5ActionPerformed
        // TODO add your handling code here:
        String v[] = new String[6];
        tabla.setNumRows(1);
        tabla.removeRow(0);
//        for(int i = 0; i < ne; i++){
//        aux.removeTableModelListener(jTableMostarEmpleado);
        
        v[0] = E1.getNombre();
        v[1] = E1.getApellido();
        v[2] = E1.getGenero();
        v[3] = E1.getFechaNac();
        v[4] = E1.getFechaIngresoEmpresa();
        v[5] = String.valueOf(E1.getSalario());
        
        tabla.addRow(v);
    }//GEN-LAST:event_jBSalarioModificar5ActionPerformed

    private void jBSalarioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalarioModificarActionPerformed
        // TODO add your handling code here:
        
        E1.setSalario(Double.parseDouble(jTSalarioModificar.getText()));
    }//GEN-LAST:event_jBSalarioModificarActionPerformed

    private void jBCalcularEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularEdadActionPerformed
        // TODO add your handling code here:
        Calendar c = Calendar.getInstance();
        String annio = Integer.toString(c.get(Calendar.YEAR));
        int year = Integer.parseInt(annio);
        String anio = E1.getFechaNac().substring(6, 10);
        int edad = year - Integer.parseInt(anio);
        jTCalcularEdad.setText(edad + "");
    }//GEN-LAST:event_jBCalcularEdadActionPerformed

    private void jBCalcularAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularAntiguedadActionPerformed
        // TODO add your handling code here:
        
        Calendar c = Calendar.getInstance();
        String annio = Integer.toString(c.get(Calendar.YEAR));
        int year = Integer.parseInt(annio);
        String anio = E1.getFechaIngresoEmpresa().substring(6, 10);
        int edad = year - Integer.parseInt(anio);
        jTCalcularAntiguedad.setText(edad + "");
    }//GEN-LAST:event_jBCalcularAntiguedadActionPerformed

    private void jBCalcularPrestacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularPrestacionActionPerformed
        // TODO add your handling code here:
        Calendar c = Calendar.getInstance();
        String annio = Integer.toString(c.get(Calendar.YEAR));
        String anio = E1.getFechaIngresoEmpresa().substring(6, 10);
        int anio2 = Integer.parseInt(anio);
        int year = Integer.parseInt(annio);
        int actual = year - anio2;
        Double res = (actual * E1.getSalario()) / 12.0;
        jTCalcularPrestacion.setText(res + "");
    }//GEN-LAST:event_jBCalcularPrestacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcularAntiguedad;
    private javax.swing.JButton jBCalcularEdad;
    private javax.swing.JButton jBCalcularPrestacion;
    private javax.swing.JButton jBSalarioModificar;
    private javax.swing.JButton jBSalarioModificar3;
    private javax.swing.JButton jBSalarioModificar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCalcularAntiguedad;
    private javax.swing.JTextField jTCalcularEdad;
    private javax.swing.JTextField jTCalcularPrestacion;
    private javax.swing.JTextField jTFechaIngreso;
    private javax.swing.JTextField jTFechaNac;
    private javax.swing.JTextField jTGenero;
    private javax.swing.JTable jTMostrarEmpleado;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTSalario;
    private javax.swing.JTextField jTSalarioModificar;
    // End of variables declaration//GEN-END:variables
}
